"""Type stubs for rpc.py — extends Connection with monkey-patched methods."""

import asyncio
import logging
import socket
from typing import Any, Callable, TypeAlias, Awaitable

class IsabelleError(Exception):
    errors: list[str]
    obj: Any
    def __init__(self, errors: list[str], errobj: Any) -> None: ...

class Connection:
    reader: asyncio.StreamReader
    writer: asyncio.StreamWriter
    sock: socket.socket
    client_addr: tuple[str, int]
    server: 'Server'
    _debug_buffer: bytearray | None
    _next_callback_id: int
    _pending: dict[int, asyncio.Future[Any]]
    _user_channel: asyncio.Queue[Any]
    _reader_task: asyncio.Task[None] | None
    _write_lock: asyncio.Lock

    @staticmethod
    def current() -> 'Connection | None': ...
    def __init__(self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter,
                 client_addr: tuple[str, int], server: 'Server') -> None: ...
    async def _feed_and_unpack(self) -> Any: ...
    async def _start_reader(self) -> None: ...
    async def read(self) -> Any: ...
    async def write(self, data: Any) -> None: ...
    async def write_error(self, error: Any) -> None: ...
    async def callback(self, name: str, arg: Any) -> Any: ...
    async def config_lookup(self, name: str) -> Any: ...
    def close(self) -> None: ...
    async def __aenter__(self) -> 'Connection': ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

    # Provided by Isabelle_RPC_Host (formerly in print, now inline)
    async def tracing(self, msg: str) -> None: ...
    async def warning(self, msg: str) -> None: ...
    async def writeln(self, msg: str) -> None: ...

    # Provided by Isabelle_RPC_Host.dialogue
    async def dialogue(self, question: str, options: list[str]) -> str: ...

    # Provided by Isabelle_Semantic_Embedding.semantics (async — uses config_lookup)
    async def semantic_vector_store(self, embedding_model: str | None = None) -> Any: ...

RemoteProcedure: TypeAlias = Callable[[Any, Connection], Awaitable[Any]]
Remote_Procedures: dict[str, RemoteProcedure]

def isabelle_remote_procedure(name: str) -> Callable[[Callable[[Any, Connection], Awaitable[Any]]], Callable[[Any, Connection], Awaitable[Any]]]: ...

class Server:
    addr: str
    host: str
    port: int
    running: bool
    debugging: bool
    logger: logging.Logger
    _server: asyncio.Server | None
    def __init__(self, addr: str, logger: logging.Logger, debugging: bool = ...) -> None: ...
    async def handle_client(self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None: ...
    async def run_server(self) -> None: ...
    def stop_server(self) -> None: ...

def isabelle_home() -> str: ...
def mk_logger_(addr: str, log_file: str | None) -> logging.Logger: ...
def launch_server_(addr: str, logger: logging.Logger, debugging: bool = ...) -> None: ...
def fork_and_launch__() -> None: ...
