"""Type stubs for rpc.py — extends Connection with monkey-patched methods."""

import logging
import socket
from typing import Any, Callable, TypeAlias

class DebugStream:
    def get_buffer_bytes(self) -> bytes: ...
    def clear_buffer(self) -> None: ...

class IsabelleError(Exception):
    errors: list[str]
    obj: Any
    def __init__(self, errors: list[str], errobj: Any) -> None: ...

class Connection:
    sock: socket.socket
    client_addr: tuple[str, int]
    server: 'Server'
    debug_stream: DebugStream | None

    @staticmethod
    def current() -> 'Connection | None': ...
    def __init__(self, socket: socket.socket, client_addr: tuple[str, int], server: 'Server') -> None: ...
    def read(self) -> Any: ...
    def write(self, data: Any) -> None: ...
    def write_error(self, error: Any) -> None: ...
    def callback(self, name: str, arg: Any) -> Any: ...
    def config_lookup(self, name: str) -> Any: ...
    def raw_callback(self, name: str, action: Callable[['Connection'], Any]) -> Any: ...
    def close(self) -> None: ...
    def __enter__(self) -> 'Connection': ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...
    def is_peer_closed(self) -> bool: ...

    # Provided by Isabelle_RPC_Host.print
    def tracing(self, msg: str) -> None: ...
    def warning(self, msg: str) -> None: ...
    def writeln(self, msg: str) -> None: ...

    # Provided by Isabelle_RPC_Host.dialogue
    def dialogue(self, question: str, options: list[str]) -> str: ...

    # Provided by Isabelle_Semantic_Embedding.semantics
    def semantic_vector_store(self, embedding_model: str | None = None) -> Any: ...

RemoteProcedure: TypeAlias = Callable[[Any, Connection], Any]
Remote_Procedures: dict[str, RemoteProcedure]

def isabelle_remote_procedure(name: str) -> Callable[[Callable[[Any, Connection], Any]], Callable[[Any, Connection], Any]]: ...

class Server:
    addr: str
    host: str
    port: int
    running: bool
    debugging: bool
    logger: logging.Logger
    def __init__(self, addr: str, logger: logging.Logger, debugging: bool = ...) -> None: ...
    def handle_client(self, client_socket: socket.socket, client_addr: tuple[str, int]) -> None: ...
    def stop_server(self) -> None: ...
    def start(self) -> None: ...

def isabelle_home() -> str: ...
def mk_logger_(name: str, level: str, log_file: str | None) -> Any: ...
def launch_server_(addr: str, modules: str, logger_name: str, log_level: str, log_file: str | None, debugging: bool) -> None: ...
def fork_and_launch__(addr: str, modules: str, logger_name: str, log_level: str, log_file: str | None, debugging: bool) -> int: ...
